api:
  url: "http://localhost:8090"

log:
  level: "Debug"
  formatter: "text"

devices:
  - "edge-dev-tse-mac"

triggering:
  - condition: "hello"
    action:
      filename: "hello-loop.py"
      url: ""
  - condition: "me"
    action:
      filename: "me-loop.py"
      url: ""

polling: 2000
